exp_setting:
  exp_name: 'GTA2City'
  snapshot_dir: 'snapshots'
  log_dir: 'log'
  use_tensorboard: True
  save_pred_every: 5000


data:
  task: 'digits'  # office, office_caltech_10, office_home, digits
  input_size: 32
  crop_size: 32
  num_classes: 10 # office:31, office_caltech_10: 10, office_home: 65
  source: ['MNIST', 'USPS', 'SYNTH', 'SVHN'] 
  target: 'MNISTM'
  num_domain: 5
  num_workers: 1


train:
  num_steps: 100000
  num_steps_stop: 50000
  batch_size: 128
  partial: False

  base_model:
    lr: 0.0001
    momentum: 0.9
  netD:
    lr: 0.0001
    momentum: 0.9
  netG:
    lr: 0.0001
    momentum: 0.9
  lr_decay_power: 0.9
  weight_decay: 0.0005
  aux_sem_thres: 0.3

  lambda:
    base_model:
      bloss_Clf:
        init: 1.
        final: 1.
        step: 1.
      bloss_AdvFeat:
        init: 0.1
        final: 0.1
        step: 1.
    netG:
      Gloss_fake:
        init: 0.02
        final: 0.02
        step: 1
      Gloss_auxsem:
        init: 0.02
        final: 0.02
        step: 1
      Gloss_dcls:
        init: 0.1
        final: 0.1
        step: 1
      Gloss_cyc:
        init: 0.1
        final: 0.1
        step: 1
    netD:
      Dloss_fakereal:
        init: 1.
        final: 1.
        step: 1
      Dloss_dcls:
        init: 10.
        final: 10.
        step: 1
      Dloss_auxsem:
        init: 10.
        final: 10.
        step: 1

  GAN:
    main: 'WGAN_GP'
    featAdv: 'Vanila'
    GP: 10
    n_critic: 5
  base: 'ResNet'  # Alex, VGG, ResNet

model:
  netG:
    norm: 'CondBN'  # CondBN, CondIN, BN, IN

