exp_setting:
  exp_name: 'GTA2City'
  snapshot_dir: 'snapshots'
  log_dir: 'log'
  use_tensorboard: True
  save_pred_every: 5000


data:
  input_size: 64
  crop_size: 64
  num_classes: 31
  source: ['Webcam', 'DSLR']
  target: 'Amazon'
  num_domain: 3
  num_workers: 1
  ignore_label: 255


train:
  num_steps: 250000
  num_steps_stop: 150000
  batch_size: 128

  base_model:
    lr: 0.00001
    momentum: 0.9
  netD:
    lr: 0.00001
    momentum: 0.9
  netG:
    lr: 0.00001
    momentum: 0.9
  lr_decay_power: 0.9
  weight_decay: 0.0005
  aux_sem_thres: 0.3

  lambda:
    classification:
      bloss_Clf:
        init: 1.
        final: 1.
        step: 1.
      bloss_AdvFeat:
        init: 0.1
        final: 0.1
        step: 1
    base_model_netG:
      bGloss_fake: 
        init: 0.02
        final: 0.02
        step: 1
      bGloss_cyc:
        init: 0.1
        final: 0.1
        step: 1
      bGloss_dcls: 
        init: 0.1
        final: 0.1
        step: 1
      bGloss_auxsem:
        init: 0.02
        final: 0.02
        step: 1
    netD:
      Dloss_fakereal:
        init: 1.
        final: 1.
        step: 1
      Dloss_dcls:
        init: 10.
        final: 10.
        step: 1
      Dloss_auxsem:
        init: 1.
        final: 1.
        step: 1

  GAN: 
    model: 'WGAN_GP'
    GP: 30
    n_critic: 5
  base: 'ResNet'  # VGG or ResNet

model:
  netD:
    conv_dim: 
      img: 32
    repeat_num:   # For downsampling (Remind PatchGAN)
      img: 5
  netG:
    conv_dim: 
      ResNet: 512
      VGG: 64
    norm: 'CondBN'
    repeat_num: 0 # For ResBlock

