exp_setting:
  exp_name: 'GTA2City'
  snapshot_dir: 'snapshots'
  log_dir: 'log'
  use_tensorboard: True
  save_pred_every: 5000


data:
  input_size: '320,320'
  crop_size: 64
  num_classes: 31
  source: ['Webcam', 'DSLR']
  target: 'Amazon'
  num_domain: 2
  num_workers: 1
  ignore_label: 255


train:
  num_steps: 250000
  num_steps_stop: 150000
  batch_size: 32

  base_model:
    lr: 0.00001
    momentum: 0.9
  netD:
    lr: 0.0001
    momentum: 0.7
  netG:
    lr: 0.00001
    momentum: 0.7
  lr_decay_power: 0.9
  weight_decay: 0.0005
  aux_sem_thres: 1.5

  lambda:
    base_model:
      bloss_Clf: 1.
      bloss_AdvFeat: 0.1
    base_model_netG:
      bGloss_fake: 0.02
      bGloss_idt: 0.
      bGloss_cyc: 0.1 # Semantic Segmentation에서는 classification loss가 크므로, 0.5~1까지는 키워줘야할 듯
      bGloss_dcls: 0.1
      bGloss_auxsem: 0.05
    netD:
      Dloss_fakereal: 1.
      Dloss_dcls: 10.
      Dloss_auxsem: 1.

  GAN: 
    model: 'WGAN_GP'
    GP: 10
    n_critic: 5
  base: 'VGG'  # VGG or ResNet


model:
  netD:
    conv_dim: 
      img: 128
    repeat_num:   # For downsampling (Remind PatchGAN)
      img: 5
  netG:
    conv_dim: 
      ResNet: 64
      VGG: 64
    norm: 'CondIN'
    repeat_num: 3  # For ResBlock

