exp_setting:
  exp_name: 'GTA2City'
  snapshot_dir: 'snapshots'
  log_dir: 'log'
  use_tensorboard: True
  save_pred_every: 5000


data:
  task: 'office_caltech_10'  # office, office_caltech_10, office_home, digits
  target: 'Amazon'
  input_size:
    digits: 32
    office_caltech_10: 256
    office_home: 256
  crop_size:
    digits: 32
    office_caltech_10: 224
    office_home: 224
  num_classes:
    digits: 10
    office_caltech_10: 10
    office_home: 65
  domain:
    digits: ['MNIST', 'USPS', 'SYNTH', 'SVHN', 'MNISTM']
    office_caltech_10: ['Amazon', 'Caltech', 'DSLR', 'Webcam']
    office_home: ['Realworld', 'Clipart', 'Product', 'Art']
  num_domain:
    digits: 5
    office_caltech_10: 4
    office_home: 4
  num_workers: 1


train:
  num_steps: 100000
  num_steps_stop: 25000
  batch_size:
    digits: 128
    office_caltech_10: 16
    office_home: 16
  partial: False
  optimizer: 
    digits: 'Adam' 
    office_caltech_10: 'Adam' 
    office_home: 'Adam' 

  base_model:
    digits:
      lr: 0.0002
      momentum: 0.9
    office_caltech_10:
      lr: 0.0001
      momentum: 0.9
    office_home:
      lr: 0.0001
      momentum: 0.9
  netD:
    digits:
      lr: 0.0002
      momentum: 0.9
    office_caltech_10:
      lr: 0.0001
      momentum: 0.9
    office_home:
      lr: 0.0001
      momentum: 0.9
  lr_decay_power:
    digits: 0.9
    office_caltech_10: 0.75
    office_home: 0.75
  weight_decay: 0.0005
  aux_sem_thres: 0.3

  lambda:
    base_model:
      bloss_Clf: 1.
      bloss_AdvFeat: 1
    netD:
      Vanila:
        D_critic: 1
      LS:
        D_critic: 1
      WGAN_GP:
        GP: 10
        D_critic: 1

  GAN:
    featAdv: 'LS'
  base: 'ResNet'  # Alex, VGG, ResNet
