exp_setting:
  exp_name: 'GTA2City'
  snapshot_dir: 'snapshots'
  log_dir: 'log'
  use_tensorboard: True
  save_pred_every: 5000


data:
  task: 'office_home'  # office, office_caltech_10, office_home
  input_size: 256
  crop_size: 224
  D_size: 64
  num_classes: 65 # office:31, office_caltech_10: 10, office_home: 65
  source: ['Art', 'Clipart', 'Product']
  target: 'Realworld'
  num_domain: 4
  num_workers: 1
  ignore_label: 255


train:
  num_steps: 100000
  num_steps_stop: 100000
  batch_size: 32
  partial: False

  base_model:
    lr: 0.0001
    momentum: 0.9
  netD:
    lr: 0.0003
    momentum: 0.7
  netG:
    lr: 0.0003
    momentum: 0.7
  lr_decay_power: 0.85
  weight_decay: 0.0005
  aux_sem_thres: 0.3

  lambda:
    base_model:
      bloss_Clf:
        init: 1.
        final: 1.
        step: 1.
      bloss_AdvFeat:
        init: 0.1
        final: 0.1
        step: 1.
    netG:
      Gloss_fake:
        init: 1.
        final: 1.
        step: 1
      Gloss_auxsem:
        init: 1.
        final: 1.
        step: 1
    base_only:
      bloss_fake:
        init: 0.01
        final: 0.01
        step: 1
      bloss_auxsem:
        init: 0.01
        final: 0.01
        step: 1
    netD:
      Dloss_fakereal:
        init: 1.
        final: 1.
        step: 1
      Dloss_auxsem:
        init: 10.
        final: 10.
        step: 1

  GAN:
    main: 'WGAN_GP'
    featAdv: 'LS'
    pixAdv: 'LS'
    GP: 30
    n_critic: 5
  base: 'ResNet'  # Alex, VGG, ResNet

model:
  netD:
    conv_dim: 
      img: 64
    repeat_num:   # For downsampling (Remind PatchGAN)
      img: 5
  netG:
    conv_dim: 
      ResNet: 128
      VGG: 64
      Alex: 64
    norm: 'BN'  # CondBN, CondIN, BN, IN

