exp_setting:
  exp_name: 'GTA2City'
  snapshot_dir: 'snapshots'
  log_dir: 'log'
  use_tensorboard: True
  save_pred_every: 5000


data:
  input_size: 300
  crop_size: 256
  num_classes: 31
  source: ['Webcam']
  target: 'DSLR'
  num_domain: 2
  num_workers: 1
  ignore_label: 255


train:
  num_steps: 250000
  num_steps_stop: 150000
  batch_size: 32

  base_model:
    lr: 0.0001
    momentum: 0.7
  netD:
    lr: 0.0001
    momentum: 0.7
  netG:
    lr: 0.0005
    momentum: 0.7
  lr_decay_power: 0.75
  weight_decay: 0.0005
  aux_sem_thres: 0.1

  lambda:
    base_model:
      bloss_Clf:
        init: 1.
        final: 1.
        step: 1.
      bloss_AdvFeat:
        init: 0.1
        final: 0.1
        step: 1
    base_model_netG:
      bGloss_fake: 
        init: 0.02
        final: 0.02
        step: 1
      bGloss_idt: 
        init: 0.
        final: 0.
        step: 1
      bGloss_cyc:
        init: 0.1
        final: 0.1
        step: 1
      bGloss_dcls: 
        init: 0.1
        final: 0.1
        step: 1
      bGloss_auxsem:
        init: 0.02
        final: 0.02
        step: 1
    netD:
      Dloss_fakereal:
        init: 1.
        final: 1.
        step: 1
      Dloss_dcls:
        init: 10.
        final: 10.
        step: 1
      Dloss_auxsem:
        init: 1.
        final: 1.
        step: 1

  GAN: 
    model: 'WGAN_GP'
    GP: 30
    n_critic: 5
  base: 'ResNet'  # VGG or ResNet

model:
  netD:
    conv_dim: 
      img: 32
    repeat_num:   # For downsampling (Remind PatchGAN)
      img: 6
  netG:
    conv_dim: 
      ResNet: 512
      VGG: 64
    norm: 'CondIN'
    repeat_num: 3  # For ResBlock

